name: Deploy to Hosted

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          port: ${{ secrets.SERVER_PORT }}
          script_stop: true
          script: |
            cd ${{ secrets.SERVER_PATH }}
            git checkout .
            git pull
            npm i
            pm2 restart pm2.config.js > /dev/null
